# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49732a99564db6024dc67cfe9ece80af5443439ef293bae7c119683ee5c27cc0f3ab6367cb5d29f040e7a991b57162242624231faf5c9340fd5c40bbee87a36c

test:
  secret_key_base: bc0dafd2ab4e76ad460a68738af22e3262a99628ecdf06690d635a22ac0a66e804f48d7b716f3904de3ace7e60f504d9eaaf13a9a9050aa0c4b19520f4f48db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
